server:
  port: 8000
paxos:
  acceptor: http://localhost:8000,http://localhost:8001,http://localhost:8002

management:
  endpoints:
    web:
      exposure:
        include:
          - shutdown
          - info
          - health
  endpoint:
    shutdown:
      enabled: true